### ISSUE TITLE
Offer release builds

### ISSUE THREAD

**Issue by wiz0u** [lambdalisue/rs-mdbook-alerts#48]
Can you offer release builds of the plugin as github release ?

Similar to what is done on https://github.com/Michael-F-Bryan/mdbook-linkcheck/releases

This would allow your plugin to be used easily in YML with the help of https://github.com/japaric/trust

**Comment by lambdalisue** [comment]
I see. Well, I need to learn the best practice to use cargo-release and GitHub Action together.

**Comment by wiz0u** [comment]
see https://github.com/Michael-F-Bryan/mdbook-linkcheck/blob/master/.github/workflows/release.yml

**Comment by lambdalisue** [comment]
Unfortunately, that doesn't help...

**Comment by 2bndy5** [comment]
> This would allow your plugin to be used easily in YML with the help of https://github.com/japaric/trust

I'm not sure how the idea stated is related to the linked project. Which YML?

---
My main aim with this comment is to help support [cargo-binstall](https://github.com/cargo-bins/cargo-binstall).

I haven't published anything to crates.io, so I'm no expert there. I am very familiar with using github actions, I've even created a few using python code.

Here's a rough draft that should
1. build the binary on several targets
2. cache the built binaries as CI artifacts (you can download these if CI is triggered from a PR)
3. create a release using [`gh-cli`](https://cli.github.com/manual/gh_release) (available on all github-hosted runner images like `ubuntu-latest`)
4. publish to crates.io [using a secret variable](https://github.com/lambdalisue/rs-mdbook-alerts/settings/secrets/actions) (named `CARGO_REGISTRY_TOKEN`) containing the [auth token for your account at crates.io](https://crates.io/settings/tokens)
5. upload the cached CI artifacts (binaries built for various targets) as release assets.

The only thing you need to do to trigger this is push a tag to the remote. I also added CI triggers to verify contribution in a PR or any push to main branch. 

> [!caution]
> This suggestion is untested and may require a prelease to verify the assets get uploaded correctly.

```yaml
name: Binary executable builds

on:
  push:
    branches: [main]
    tags:
      - v[0-9]+.*
  pull_request:
    branches: [main]

jobs:

  create-assets:
    name: ${{ matrix.target }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-latest
          - target: aarch64-unknown-linux-musl
            os: ubuntu-latest
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - target: x86_64-unknown-linux-musl
            os: ubuntu-latest
          - target: aarch64-apple-darwin
            os: macos-latest
          - target: x86_64-apple-darwin
            os: macos-latest
          - target: x86_64-pc-windows-msvc
            os: windows-latest
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    steps:
      - name: Calculate Release Version
        id: calc-version
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            short_sha=$(echo "${{ github.sha }}" | awk '{print substr($0,0,5)}')
            echo "RELEASE_VERSION=nightly-$(date '+%Y-%m-%d')-$short_sha" >> $GITHUB_OUTPUT
          else
            echo "RELEASE_VERSION=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          fi

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          target: ${{ matrix.target }}

      - name: Build
        run: cargo build --release --bin mdbook-alerts --target ${{ matrix.target }}

      - name: Prepare artifacts [Windows]
        shell: bash
        if: matrix.os == 'windows-latest'
        id: prep-artifacts-windows
        run: |
          release_dir="${{ steps.calc-version.outputs.RELEASE_VERSION }}"
          artifact_path="${{ steps.calc-version.outputs.RELEASE_VERSION }}-${{ matrix.target }}.zip"
          echo "ARTIFACT_PATH=$artifact_path" >> $GITHUB_OUTPUT
          mkdir $release_dir
          cp target/${{ matrix.target }}/release/mdbook-alerts.exe $release_dir/
          cp LICENSE $release_dir/
          7z a -tzip $artifact_path $release_dir/

      - name: Prepare artifacts [Unix]
        shell: bash
        id: prep-artifacts-unix
        if: matrix.os != 'windows-latest'
        run: |
          release_dir="mdbook-alerts_${{ steps.calc-version.outputs.RELEASE_VERSION }}"
          artifact_path="mdbook-alerts_${{ steps.calc-version.outputs.RELEASE_VERSION }}-${{ matrix.target }}.tar.gz"
          echo "ARTIFACT_PATH=$artifact_path" >> $GITHUB_OUTPUT
          mkdir $release_dir
          cp target/${{ matrix.target }}/release/mdbook-alerts $release_dir/
          cp LICENSE $release_dir
          tar -czvf $artifact_path $release_dir/

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.prep-artifacts-unix.outputs.ARTIFACT_PATH || steps.prep-artifacts-windows.outputs.ARTIFACT_PATH }}
          path: ${{ steps.prep-artifacts-unix.outputs.ARTIFACT_PATH || steps.prep-artifacts-windows.outputs.ARTIFACT_PATH }}
          if-no-files-found: error

  create-release:
    if: startswith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    needs: [create-assets]
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Install Rust
        run: rustup update stable --no-self-update
      - run: cargo package
      - name: Create a Github Release
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh release create ${{ github.ref_name }} --generate-notes
      - run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

  upload-assets:
    needs: [create-release]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - aarch64-unknown-linux-gnu
          - aarch64-unknown-linux-musl
          - x86_64-unknown-linux-gnu
          - x86_64-unknown-linux-musl
          - aarch64-apple-darwin
          - x86_64-apple-darwin
          - x86_64-pc-windows-msvc
    steps:
      - name: Download build asset
        uses: actions/download-artifact@v4
        with:
          pattern: mdbook-alerts_*
          path: dist
      - name: Upload release assets
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          files=$ls dist/mdbook-alerts_*
          gh release upload ${{ github.ref_name }} $files --clobber

```

Finally, you can make the crates.io release [compatible with cargo-binstall](https://github.com/cargo-bins/cargo-binstall/blob/main/SUPPORT.md) by adding the following to your Cargo.toml:
```toml
[package.metadata.binstall]
pkg-url = "{ repo }/releases/download/v{ version }/{ name }-{ target }-v{ version }{ archive-suffix }"
bin-dir = "{ name }-{ target }-v{ version }/{ bin }{ binary-ext }"
pkg-fmt = "tgz"
```

**Comment by wiz0u** [comment]
> I'm not sure how the idea stated is related to the linked project. Which YML?

using such lines in ci.yml while building the github pages book:
```
    - name: Install mdbook-alerts
      run: |
        curl -LSfs https://japaric.github.io/trust/install.sh | \
          sh -s -- --git lambdalisue/rs-mdbook-alerts

```

but this only works if the projects has github releases package

**Comment by 2bndy5** [comment]
Oh, I think cargo-binstall support is a much more worthwhile effort. It poses the same requirements with some extra consideration toward system architecture. Although, I'm not familiar with this project's dependency tree. There might be some targets that won't cross compile with just `cargo build` due to dependencies of dependencies (sys crates or those with customized build scripts)... All the targets used in my drafted suggestion should already be at tier 1 support.

**Comment by wiz0u** [comment]
Loading rust & cargo and compiling/building all that (with a curl | sh) just for a mdbook addon takes too much time IMHO. I would much prefer a prebuilt binaries solution.

**Comment by 2bndy5** [comment]
FYI, github runners already have rust/cargo installed.

**Comment by wiz0u** [comment]
Indeed, but it still takes 1m24sec to download/compile when it would take just 2secs for using a compiled binary.
(and for a continuous delivery action, it makes sense to want to see the result fast)

**Comment by 2bndy5** [comment]
Try this:
```yml
      - name: Install cargo-binstall
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-binstall

      - name: Install mdbook
        run: cargo binstall -y mdbook
```
It doesn't rely on illegible bash commands and only compiles mdbook if it can't be downloaded from release assets.

The real problem we're both trying to resolve is the fact that cargo itself doesn't provide a fast delivery system for released binary packages. That's where cargo-binstall comes in to save the day.
